export const audioFiles = {
  "Ahoj! / Čau!": "assets/audio/000.wav",
  "Ahojte! / Čaute!": "assets/audio/001.wav",
  "Aj tebe!": "assets/audio/002.wav",
  "Aj vám!": "assets/audio/003.wav",
  "Ako sa máš?": "assets/audio/004.wav",
  "Ako sa máte?": "assets/audio/005.wav",
  "Ako sa voláš?": "assets/audio/006.wav",
  "Ako sa voláte?": "assets/audio/007.wav",
  "Áno": "assets/audio/008.wav",
  "Nie": "assets/audio/009.wav",
  "Dobré ráno!": "assets/audio/010.wav",
  "Dobrý deň!": "assets/audio/011.wav",
  "Dobrý večer!": "assets/audio/012.wav",
  "Dobrú noc!": "assets/audio/013.wav",
  "Dobrú chuť!": "assets/audio/014.wav",
  "Dovidenia!": "assets/audio/015.wav",
  "Ďakujem!": "assets/audio/016.wav",
  "Mám sa dobre.": "assets/audio/017.wav",
  "Mám sa výborne.": "assets/audio/018.wav",
  "Mám sa zle.": "assets/audio/019.wav",
  "Maj sa dobre.": "assets/audio/020.wav",
  "Na zdravie!": "assets/audio/021.wav",
  "Nech sa páči.": "assets/audio/022.wav",
  "Nič sa nestalo.": "assets/audio/023.wav",
  "Pekný deň.": "assets/audio/024.wav",
  "Prepáč / Prepáčte": "assets/audio/025.wav",
  "Prosím?": "assets/audio/026.wav",
  "Prosím.": "assets/audio/027.wav",
  "Šťastnú cestu!": "assets/audio/028.wav",
  "Teší ma.": "assets/audio/029.wav",
  "Vitajte na Slovensku!": "assets/audio/030.wav",
  "Volám sa...": "assets/audio/031.wav",
  "hovoriť": "assets/audio/032.wav",
  "slovenčina": "assets/audio/033.wav",
  "Hovoríš po slovensky?": "assets/audio/034.wav",
  "Hovoríte po slovensky?": "assets/audio/035.wav",
  "Rozumiete po slovensky?": "assets/audio/036.wav",
  "Koľko máš rokov?": "assets/audio/037.wav",
  "Koľko máte rokov?": "assets/audio/038.wav",
  "Odkiaľ si?": "assets/audio/039.wav",
  "Odkiaľ ste?": "assets/audio/040.wav",
  "meno": "assets/audio/041.wav",
  "priezvisko": "assets/audio/042.wav",
  "slečna": "assets/audio/043.wav",
  "manažér": "assets/audio/044.wav",
  "obyvateľ": "assets/audio/045.wav",
  "ja": "assets/audio/046.wav",
  "ty": "assets/audio/047.wav",
  "on": "assets/audio/048.wav",
  "ona": "assets/audio/049.wav",
  "ono": "assets/audio/050.wav",
  "my": "assets/audio/051.wav",
  "vy": "assets/audio/052.wav",
  "oni / ony": "assets/audio/053.wav",
  "ja som": "assets/audio/054.wav",
  "ty si": "assets/audio/055.wav",
  "on / ona / ono je": "assets/audio/056.wav",
  "my sme": "assets/audio/057.wav",
  "vy ste": "assets/audio/058.wav",
  "oni / ony sú": "assets/audio/059.wav",
  "Som z Kazachstanu.": "assets/audio/060.wav",
  "Som zo Slovenska.": "assets/audio/061.wav",
  "toto": "assets/audio/062.wav",
  "to": "assets/audio/063.wav",
  "tamto": "assets/audio/064.wav",
  "slobodný": "assets/audio/065.wav",
  "žena": "assets/audio/066.wav",
  "dievča": "assets/audio/067.wav",
  "chlapec": "assets/audio/068.wav",
  "Slovensko": "assets/audio/069.wav",
  "Česko": "assets/audio/070.wav",
  "Poľsko": "assets/audio/071.wav",
  "Maďarsko": "assets/audio/072.wav",
  "Rusko": "assets/audio/073.wav",
  "Francúzsko": "assets/audio/074.wav",
  "Taliansko": "assets/audio/075.wav",
  "Nemecko": "assets/audio/076.wav",
  "Španielsko": "assets/audio/077.wav",
  "Ukrajina": "assets/audio/078.wav",
  "Amerika": "assets/audio/079.wav",
  "Európa": "assets/audio/080.wav",
  "zo Slovenska": "assets/audio/081.wav",
  "z Kazachstanu": "assets/audio/082.wav",
  "miestnosť": "assets/audio/083.wav",
  "kniha": "assets/audio/084.wav",
  "počítač": "assets/audio/085.wav",
  "kľúč": "assets/audio/086.wav",
  "pes": "assets/audio/087.wav",
  "spolubývajúci": "assets/audio/088.wav",
  "poschodie": "assets/audio/089.wav",
  "pracovať": "assets/audio/090.wav",
  "rozumieť": "assets/audio/091.wav",
  "študovať": "assets/audio/092.wav",
  "robiť": "assets/audio/093.wav",
  "mäkký": "assets/audio/094.wav",
  "lacný": "assets/audio/095.wav",
  "dlhý": "assets/audio/096.wav",
  "krátky": "assets/audio/097.wav"
};
