// Exercise content and answer rules are independent of profiles and rendering.
const forms=[['Ja','som','nie som'],['Ty','si','nie si'],['On','je','nie je'],['Ona','je','nie je'],['Ono','je','nie je'],['My','sme','nie sme'],['Vy','ste','nie ste'],['Oni','sú','nie sú'],['Ony','sú','nie sú']];
const gaps=forms.flatMap(([pronoun,yes,no])=>[false,true].map(negative=>({
 sk:`${pronoun} ${negative?no:yes} zo Slovenska.`,ru:negative?'Отрицание: не из Словакии':'Утверждение: из Словакии',
 prompt:`${pronoun} ___ (byť) zo Slovenska.`,answers:[negative?no:yes],exercise:'gap',type:'grammar',lessonId:'byt',lessonTitle:'Byť / nebyť',infinitive:'byť',context:negative?'Вставьте отрицательную форму глагола из скобок.':'Вставьте глагол из скобок в правильной форме.'
})));
const scenes=[
 ['В поезде','Вы входите в купе днём. Поздоровайтесь с незнакомым взрослым пассажиром.','Dobrý deň!'],
 ['В поезде','Пассажир спрашивает, как у вас дела. Ответьте: «У меня всё хорошо».','Mám sa dobre.'],
 ['В поезде','Вы выходите из поезда. Попрощайтесь с незнакомым пассажиром: «До свидания!»','Dovidenia!'],
 ['В поезде','Пожелайте попутчику счастливого пути.','Šťastnú cestu!'],
 ['В университете','Вы знакомитесь с одногруппником. Спросите на «ты»: «Как тебя зовут?»','Ako sa voláš?'],
 ['В университете','Одногруппник представился. Скажите: «Очень приятно».','Teší ma.'],
 ['В университете','Спросите одногруппника на «ты»: «Откуда ты?»','Odkiaľ si?'],
 ['В университете','Спросите преподавателя вежливо: «Вы говорите по-словацки?»','Hovoríte po slovensky?'],
 ['После занятий','Вы прощаетесь с другом. Скажите: «Береги себя».','Maj sa dobre.'],
 ['В столовой','Одногруппник начинает обед. Пожелайте приятного аппетита.','Dobrú chuť!']
].map(([scene,context,sk])=>({scene,context,sk,ru:context,answers:[sk],exercise:'situation',type:'phrase',lessonId:'situations',lessonTitle:'Живые ситуации'}));
const screenshotGaps=[
 ['Ja ___ študent.','som','Ja → som.'],['Ty ___ veľmi milý.','si','Ty → si.'],['On ___ doma.','je','On → je.'],['My ___ z Bratislavy.','sme','My → sme.'],['Vy ___ unavení?','ste','Vy → ste, в том числе в вопросе.'],['Oni ___ v škole.','sú','Oni → sú. Не забывайте долгую ú.'],['Jana ___ moja sestra.','je','Jana — она: ona je.'],['Peter a ja ___ kamaráti.','sme','Peter a ja — мы: my sme.'],['To ___ dobrý nápad.','je','To → je.'],['Vy ___ pán učiteľ?','ste','Вежливое обращение к одному человеку: vy ste.']
].map(([prompt,answer,explanation])=>({sk:prompt.replace('___',answer),ru:'Вставьте форму byť',prompt,answers:[answer],explanation,exercise:'gap',type:'grammar',lessonId:'byt',lessonTitle:'Byť: предложения',context:'Введите только пропущенную форму глагола.'}));
const pronounGroups=[['Johana, Carlo, Zuzana, Róbert','oni'],['Carlo, Zuzana','oni'],['Johana, Zuzana','ony'],['Carlo, Róbert','oni'],['Jana, Anna','ony'],['Peter, Jana','oni'],['deti','ony'],['knihy','ony'],['muži','oni'],['ženy','ony']].map(([group,answer])=>({sk:`${group} → ${answer}`,ru:'Выберите местоимение',prompt:group,answers:[answer],exercise:'pronoun',type:'grammar',lessonId:'pronouns',lessonTitle:'Oni / ony',context:'Введите oni или ony.',explanation:answer==='oni'?'Oni: мужчины или группа людей, в которой есть мужчина.':'Ony: женщины; также deti (дети) и неодушевлённые предметы.'}));
export const exerciseItems=[...screenshotGaps,...gaps.filter(i=>i.ru.startsWith('Отрицание')),...pronounGroups,...scenes];
export const normalizeAnswer=s=>s.normalize('NFC').toLocaleLowerCase('sk').trim().replace(/[.!?,…]+$/u,'').replace(/\s+/g,' ');
export function slovakVoice(){return window.speechSynthesis?.getVoices().find(v=>/^sk(?:[-_]|$)/i.test(v.lang))||null}
function answersFor(i){
 if(i.answers)return i.answers;
 // Slash groups can contain pronouns sharing a verb: “on / ona / ono je”.
 if(i.sk==='on / ona / ono je')return ['on je','ona je','ono je'];
 if(i.sk==='oni / ony sú')return ['oni sú','ony sú'];
 return i.sk.split(/\s*\/\s*/);
}
export function makeQuestion(i,mode,index,pool){
 if(['gender','choice'].includes(i.exercise))return {mode:'categories',prompt:i.prompt,answers:i.answers,title:i.exercise==='gender'?'Распределите по роду':'Выберите ответ',opts:i.options.map(x=>({sk:x,ru:x}))};
 if(i.exercise)return {mode:'write',prompt:i.prompt||i.context,context:i.exercise==='situation'?i.scene:i.context,answers:answersFor(i),title:i.exercise==='gap'?'Вставьте форму глагола':i.exercise==='pronoun'?'Дополните: oni / ony':i.exercise==='translation'?'Напишите перевод':'Ответьте по ситуации'};
 const chosen=mode==='mixed'?(index%3===2?'choice':'write'):mode;
 if(chosen==='choice')return {mode:'choice',prompt:i.sk,answers:[i.sk],title:'Выберите перевод',opts:[i,...pool.filter(x=>!x.exercise&&x.sk!==i.sk&&x.ru!==i.ru).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5)};
 return {mode:'write',prompt:i.ru,answers:answersFor(i),title:'Напишите по-словацки',context:'Если указано несколько вариантов, достаточно одного.'};
}
export function trainingMenu(lessons,count){const tiles=[['write','writing','Написать 10 слов','Переводите с русского без вариантов ответа. Буквы и диакритика важны.'],['mixed','tasks','10 разных заданий','Ввод перевода чередуется с выбором ответа.'],['grammar','byt','Byť / nebyť','10 предложений из урока и 9 заданий на отрицание с nie.'],['pronouns','oni','Oni / ony','Группы людей, дети и предметы: впишите нужное местоимение.'],['situation','situations','10 живых ситуаций','Поезд, университет, столовая. Напишите подходящую фразу.']];return `<div class="practice-shell practice-menu"><div class="page-heading practice-heading"><div><p class="eyebrow">ВСПОМИНАЙТЕ, ПИШИТЕ, ОБЩАЙТЕСЬ</p><h1>Практика</h1><p>Выберите тему и формат. Если в теме меньше 10 карточек, пройдите все.</p></div><div class="practice-header-art" aria-hidden="true"><img class="practice-heading-art" src="src/assets/illustrations/mascot-reading.png" alt=""><img class="practice-flag" src="src/assets/illustrations/slovakia-flag.png" alt=""></div></div><div class="topic-panel"><label class="field-label" for="practiceTopic">Темы для своей и смешанной тренировки</label><select id="practiceTopic" class="field-select"><option value="all">Все уроки и собственные слова</option>${lessons.map(l=>`<option value="${l.id}">${l.title}</option>`).join('')}</select></div><div class="training-grid">${lessons.some(l=>l.customLesson)?'<button data-train="lesson" class="training-tile"><span class="training-icon"><img class="training-art" src="assets/icons/book.png" alt=""></span><span class="training-copy"><b>Задания выбранного урока</b><span>Слова, род и пропуски из новых материалов.</span></span><span class="tile-arrow">→</span></button>':''}${tiles.map(([mode,asset,title,copy])=>`<button data-train="${mode}" class="training-tile"><span class="training-icon"><img class="training-art" src="src/assets/illustrations/practice-${asset}.png" alt="" aria-hidden="true"></span><span class="training-copy"><b>${title}</b><span>${copy}</span></span><span class="tile-arrow"><i class="bi bi-arrow-right" aria-hidden="true"></i></span></button>`).join('')}</div><button class="scheduled-review" data-action="start-review" ${count?'':'disabled'}><span class="training-icon"><img class="training-art" src="assets/icons/repeat.png" alt="" aria-hidden="true"></span><span class="training-copy"><b>Повторение по расписанию</b><span>Слова, которые пора повторить, на основе ваших ответов.</span></span><span class="tile-arrow"><i class="bi bi-arrow-right" aria-hidden="true"></i></span></button></div>`}
export function questionHTML(s,esc){const q=s.question,i=s.items[s.index],correctOption=o=>q.mode==='categories'?q.answers.includes(o.sk):o.sk===i.sk;return `<div class="practice-shell"><div class="practice-progress" data-session="${s.serial}"><button class="practice-close" data-action="quit" aria-label="Закончить">×</button><div class="progress-track" role="progressbar" aria-label="Прогресс тренировки" aria-valuemin="0" aria-valuemax="${s.items.length}" aria-valuenow="${s.index+Number(s.answered&&s.ok)}"><div class="progress-fill" style="transform:scaleX(${(s.index+Number(s.answered&&s.ok))/s.items.length})"></div></div><span class="practice-counter">${s.index+1} / ${s.items.length}</span></div><div class="question-content"><h1 class="question-title">${esc(q.title)}</h1><p class="question-hint">${esc(q.context||(q.mode==='categories'?'Выберите подходящую группу.':i.exercise==='gap'?'Вставьте глагол из скобок в правильной форме.':q.mode==='write'?'Напишите ответ на словацком.':'Выберите правильный перевод.'))}</p><section class="question-card"><div class="question-prompt"><strong>${esc(q.prompt)}</strong></div>${q.mode==='write'?`<form id="answerForm"><label class="field-label" for="writtenAnswer">Ваш ответ на словацком</label><input id="writtenAnswer" class="written-answer" autocomplete="off" autocapitalize="off" spellcheck="false" required maxlength="200" value="${s.answered?esc(s.selected):''}" ${s.answered?'disabled':''}><div class="accent-keys">${[...'áäčďéíĺľňóôŕšťúýž'].map(c=>`<button type="button" data-char="${c}" ${s.answered?'disabled':''}>${c}</button>`).join('')}</div><p class="answer-note">Регистр и знак в конце не важны. Диакритика проверяется: á, č, š…</p>${s.answered?'':'<button class="primary-button" type="submit">Проверить ↵</button>'}</form>`:`<div class="answer-options">${q.opts.map(o=>`<button class="answer-option ${s.answered&&(s.ok||s.reveal)&&correctOption(o)?'correct':''} ${s.answered&&s.selected===o.sk&&!correctOption(o)?'wrong':''}" data-answer="${esc(o.sk)}" ${s.answered?'disabled':''}>${esc(o.ru)}</button>`).join('')}</div>`}${s.answered?`<div class="feedback ${s.ok?'correct':'wrong'}" role="status" aria-live="polite">${s.ok?'✓ Правильно!':`Ваш ответ: <b>${esc(s.selected)}</b><br>${s.reveal?`Правильный ответ: <b>${esc(q.mode==='choice'?i.ru:q.answers.join(' / '))}</b>`:'Пока неверно. Попробуйте ещё раз.'}`}${i.explanation&&(s.ok||s.reveal)?`<br>${esc(i.explanation)}`:''}</div>`:''}</section>${s.answered?`<div class="practice-actions">${s.ok?'<button class="primary-button" data-action="next">Продолжить →</button>':`<button class="primary-button" data-action="retry">Попробовать снова</button><button class="quiet-button" data-action="${s.reveal?'next':'show-answer'}">${s.reveal?'Продолжить →':'Показать ответ'}</button>`}</div>`:''}</div></div>`}
