import {ruleCard} from './rule-cards.js?v=20261005-red2';
import {packages,newPackage,newId,validatePackage,savePackage,savePackages,canEdit,cloudEnabled,signIn,signOut,loadContent} from './content-store.js';
let editing=null,preview=null,batch=null,message='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label={draft:'Черновик',published:'Опубликован',archived:'В архиве'};
const input=(name,value,placeholder='')=>`<input name="${name}" value="${esc(value)}" placeholder="${esc(placeholder)}" required>`;
function exerciseRow(e){return `<fieldset class="exercise-editor" data-exercise-id="${esc(e.id)}"><legend>Задание</legend><label>Формат<select name="exercise-type">${[['gap','Пропуск в предложении'],['translation','Перевод'],['gender','Определить род'],['choice','Выбор ответа'],['situation','Ситуация']].map(([v,t])=>`<option value="${v}" ${e.type===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Условие${input('exercise-prompt',e.prompt,'Ja ___ študent.')}</label><label>Правильный ответ (несколько вариантов — через |)${input('exercise-answers',e.answers.join(' | '),'som')}</label><label>Варианты для выбора (через |)<input name="exercise-options" value="${esc(e.options?.join(' | ')||'')}" placeholder="mužský rod | ženský rod | stredný rod"></label><label>Объяснение после ответа<input name="exercise-explanation" value="${esc(e.explanation||'')}"></label><button type="button" class="quiet-button" data-manager="remove-exercise" data-id="${esc(e.id)}">Убрать задание</button></fieldset>`}
function editor(){return `<form id="lesson-editor" class="manager-editor"><h2>${editing.title?'Редактирование урока':'Новый урок'}</h2><label>Название${input('lesson-title',editing.title,'Урок 2 — Общежитие и университет')}</label><label>Описание<input name="lesson-description" value="${esc(editing.description)}"></label><label>Добавить новые слова: одна пара на строку<textarea name="lesson-words" rows="8" placeholder="kniha — книга"></textarea></label><p class="manager-hint">При исправлении перевода карточка сохраняет прогресс. Для изменения слова используйте поля карточек ниже.</p>${editing.words.map(w=>`<div class="word-id-editor" data-word-id="${esc(w.id)}"><input name="word-sk" value="${esc(w.sk)}" aria-label="Словацкое слово"><input name="word-ru" value="${esc(w.ru)}" aria-label="Перевод"><label class="word-audio-label">${w.audio?'Озвучка добавлена':'Добавить озвучку'}<input type="file" accept="audio/wav,audio/mpeg,audio/mp4" data-audio-word="${esc(w.id)}"></label><button type="button" class="quiet-button" data-manager="remove-word" data-id="${esc(w.id)}">Убрать</button></div>`).join('')}<h3>Правила</h3>${editing.rules.map(r=>`<fieldset data-rule-id="${esc(r.id)}"><label>Название${input('rule-title',r.title)}</label><label>Объяснение<textarea name="rule-text" rows="5" required>${esc(r.text)}</textarea></label><button type="button" class="quiet-button" data-manager="remove-rule" data-id="${esc(r.id)}">Убрать правило</button></fieldset>`).join('')}<button type="button" class="quiet-button" data-manager="add-rule">+ Правило</button><h3>Упражнения</h3>${editing.exercises.map(exerciseRow).join('')}<button type="button" class="quiet-button" data-manager="add-exercise">+ Задание</button><div class="manager-actions"><button type="submit" class="primary-button">Предпросмотр</button><button type="button" class="quiet-button" data-manager="cancel">Отмена</button></div></form>`}
function previewHTML(){if(batch)return `<section class="panel manager-preview"><h2>Восстановление материалов</h2><p>${batch.length} уроков. Существующие уроки с такими же id будут обновлены.</p>${batch.map(p=>`<article class="rule-preview"><h3>${esc(p.title)}</h3><p>${label[p.status]} · ${p.words.length} слов · ${p.exercises.length} заданий</p></article>`).join('')}<div class="manager-actions"><button class="primary-button" data-manager="restore-batch">Восстановить</button><button class="quiet-button" data-manager="cancel">Отмена</button></div></section>`;const duplicate=packages.some(p=>p.id===preview.id);return `<section class="manager-preview panel"><h2>${esc(preview.title)}</h2><p>${esc(preview.description)}</p><p>Слова: ${preview.words.length} · Правила: ${preview.rules.length} · Задания: ${preview.exercises.length}</p>${duplicate?'<p class="manager-hint">Это обновление существующего урока. Его постоянные идентификаторы и прогресс сохранятся.</p>':''}<div class="content-list">${preview.words.map(w=>`<div class="content-row"><b>${esc(w.sk)}</b><span>${esc(w.ru)}</span></div>`).join('')}</div>${preview.rules.map(ruleCard).join('')}${preview.exercises.map(e=>`<article class="rule-preview"><h3>${esc(e.prompt)}</h3><p>Ответ: ${esc(e.answers.join(' / '))}</p><p>${esc(e.explanation)}</p></article>`).join('')}<div class="manager-actions"><button class="primary-button" data-manager="save-draft">Сохранить черновик</button><button class="primary-button" data-manager="publish-preview">Опубликовать</button><button class="quiet-button" data-manager="edit-preview">Редактировать</button></div></section>`}
export function managerHTML(){return `<div class="manager-page"><button class="back-button" data-view="lessons">← Уроки</button><h1>Материалы курса</h1><p>Добавляйте уроки и задания без пересборки сайта.</p>${message?`<p class="manager-message" role="status">${esc(message)}</p>`:''}${!canEdit()?`<form id="editor-login" class="manager-editor"><h2>Вход редактора</h2><label>Email<input name="email" type="email" required autocomplete="username"></label><label>Пароль<input name="password" type="password" required autocomplete="current-password"></label><button class="primary-button">Войти</button></form>`:`${editing?editor():(preview||batch)?previewHTML():`<div class="manager-actions"><button class="primary-button" data-manager="new">+ Новый урок</button><label class="quiet-button import-label">Импорт урока<input type="file" id="lesson-import" accept=".json,application/json"></label><button class="quiet-button" data-manager="export-all">Скачать все уроки</button><button class="quiet-button" data-manager="refresh">Обновить список</button>${cloudEnabled()?'<button class="quiet-button" data-manager="logout">Выйти</button>':''}</div><div class="manager-list">${packages.map(p=>`<article class="panel manager-card"><div><h2>${esc(p.title)}</h2><span class="tiny-pill">${label[p.status]}</span><p>Слова: ${p.words.length} · Правила: ${p.rules.length} · Задания: ${p.exercises.length}</p></div><div class="manager-actions"><button class="quiet-button" data-manager="edit" data-id="${esc(p.id)}">Редактировать</button><button class="quiet-button" data-manager="export" data-id="${esc(p.id)}">Скачать</button><button class="quiet-button" data-manager="${p.status==='published'?'unpublish':'publish'}" data-id="${esc(p.id)}">${p.status==='published'?'В черновики':'Опубликовать'}</button>${p.status!=='archived'?`<button class="quiet-button" data-manager="archive" data-id="${esc(p.id)}">В архив</button>`:''}</div></article>`).join('')||'<p>Пока нет добавленных уроков.</p>'}</div>`}`}</div>`}
function readEditor(){const f=document.querySelector('#lesson-editor');if(!f||!editing)return;const value=n=>f.elements.namedItem(n)?.value||'';
 editing.title=value('lesson-title');editing.description=value('lesson-description');
 const old=editing.words;
 editing.words=[...f.querySelectorAll('[data-word-id]')].map(row=>({...old.find(w=>w.id===row.dataset.wordId),sk:row.querySelector('[name=word-sk]').value.trim(),ru:row.querySelector('[name=word-ru]').value.trim()}));
 for(const [n,line] of value('lesson-words').split('\n').filter(s=>s.trim()).entries()){const match=line.match(/^(.+?)\s+[—–]\s+(.+)$/);if(!match)throw Error(`Строка ${n+1}: используйте «слово — перевод».`);const sk=match[1].trim(),ru=match[2].trim();if(editing.words.some(w=>w.sk.toLocaleLowerCase('sk')===sk.toLocaleLowerCase('sk')))throw Error(`Слово ${sk} повторяется в уроке.`);editing.words.push({id:newId(),type:sk.includes(' ')?'phrase':'word',sk,ru});}
 editing.rules=[...f.querySelectorAll('[data-rule-id]')].map(row=>({...editing.rules.find(r=>r.id===row.dataset.ruleId),id:row.dataset.ruleId,title:row.querySelector('[name=rule-title]').value,text:row.querySelector('[name=rule-text]').value}));
 const split=s=>s.split('|').map(s=>s.trim()).filter(Boolean);
 editing.exercises=[...f.querySelectorAll('[data-exercise-id]')].map(row=>({id:row.dataset.exerciseId,type:row.querySelector('[name=exercise-type]').value,prompt:row.querySelector('[name=exercise-prompt]').value,answers:split(row.querySelector('[name=exercise-answers]').value),options:split(row.querySelector('[name=exercise-options]').value),explanation:row.querySelector('[name=exercise-explanation]').value}));
}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export async function managerClick(button){message='';const action=button.dataset.manager,p=packages.find(p=>p.id===button.dataset.id);
 if(['add-rule','add-exercise','remove-rule','remove-exercise','remove-word'].includes(action))readEditor();
 if(action==='new'){editing=newPackage();preview=null}
 if(action==='edit'){editing=structuredClone(p);preview=null}
 if(action==='edit-preview'){editing=structuredClone(preview);preview=null}
 if(action==='cancel'){editing=null;preview=null;batch=null}
 if(action==='add-rule')editing.rules.push({id:newId(),title:'',text:''});
 if(action==='add-exercise')editing.exercises.push({id:newId(),type:'gap',prompt:'',answers:[],options:[],explanation:''});
 if(action==='remove-word')editing.words=editing.words.filter(w=>w.id!==button.dataset.id);
 if(action==='remove-rule')editing.rules=editing.rules.filter(r=>r.id!==button.dataset.id);
 if(action==='remove-exercise')editing.exercises=editing.exercises.filter(r=>r.id!==button.dataset.id);
 if(action==='restore-batch'){await savePackages(batch);batch=null;message='Материалы восстановлены.'}
 if(action==='export')download(p,`${p.id}.json`);
 if(action==='export-all')download({schemaVersion:1,packages},'slovicko-lessons.json');
 if(action==='refresh'){await loadContent();message='Список обновлён.'}
 if(action==='logout')await signOut();
 if(action==='publish'){preview=structuredClone(p);editing=null;return;}
 if(['unpublish','archive'].includes(action)){await savePackage({...p,status:action==='publish'?'published':action==='unpublish'?'draft':'archived'});message='Статус урока сохранён.'}
 if(['save-draft','publish-preview'].includes(action)){await savePackage({...preview,status:action==='save-draft'?'draft':'published'});editing=null;preview=null;message=action==='save-draft'?'Черновик сохранён.':'Урок появился в курсе.'}
}
export async function managerSubmit(form){message='';if(form.id==='lesson-editor'){readEditor();preview=validatePackage(editing);editing=null;}if(form.id==='editor-login'){await signIn(form.elements.email.value,form.elements.password.value);message='Вы вошли. Изменять материалы может только владелец курса.'}}
export async function managerImport(file){if(file.size>2_000_000)throw Error('Размер файла — до 2 МБ.');const raw=JSON.parse(await file.text());if(raw.packages){if(raw.schemaVersion!==1||!Array.isArray(raw.packages)||!raw.packages.length)throw Error('Некорректный архив уроков.');batch=raw.packages.map(validatePackage);editing=null;preview=null;message='Проверьте список перед восстановлением.';return;}batch=null;preview=validatePackage(raw);editing=null;message='Пакет прочитан. Проверьте ответы перед публикацией.'}
export function managerError(error){message=error.message||'Не удалось выполнить действие.'}

export async function managerAudio(input){readEditor();const file=input.files[0];if(!file)return;if(file.size>400000)throw Error('Запись должна быть короче: до 400 КБ.');if(!['audio/wav','audio/x-wav','audio/mpeg','audio/mp4'].includes(file.type))throw Error('Загрузите WAV, MP3 или M4A.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const word=editing.words.find(w=>w.id===input.dataset.audioWord);if(word)word.audio=data;message='Запись добавлена. Она сохранится вместе с уроком.';}
