const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function verbHighlight(text,index,title=false){
 const stems=title?['VOL','HOVOR','ŠTUD','ROZUM']:['vol','hovor','štud','rozum'];
 const value=String(text),stem=stems[index];
 if(!stem||!value.startsWith(stem))return esc(value);
 if(title){const tail=value.slice(stem.length),cut=tail.indexOf('Ť');if(cut>=0)return `${esc(stem)}<span class="verb-ending">${esc(tail.slice(0,cut))}</span>${esc(tail.slice(cut))}`;}
 const tail=value.slice(stem.length),space=tail.indexOf(' '),ending=space<0?tail:tail.slice(0,space),rest=space<0?'':tail.slice(space);
 return `${esc(stem)}<span class="verb-ending">${esc(ending)}</span>${esc(rest)}`;
}
export function ruleCard(rule){const v=rule.visual;
 if(v?.format==='reference-table'&&Array.isArray(v.headers)&&Array.isArray(v.rows))return `<article class="visual-rule reference-table-rule"><h3>${esc(rule.title)}</h3><div class="rule-table-scroll"><table><thead><tr>${v.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${v.rows.map(row=>`<tr>${row.map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="reference-rule-note">${esc(rule.text)}</p></article>`;
 if(v?.format==='gender'&&v.image==='rule-rod.png')return `<article class="visual-rule image-rule"><h3>${esc(rule.title)}</h3><a href="src/assets/illustrations/rule-rod.png" target="_blank" rel="noopener" aria-label="Открыть таблицу рода в полном размере"><img class="grammar-sheet" src="src/assets/illustrations/rule-rod.png" alt="Substantíva – rod: мужской, женский и средний род, окончания, примеры и исключения"></a><details class="rule-details"><summary>Полное объяснение</summary><p>${esc(rule.text)}</p></details></article>`;
 if(v?.format==='gender'&&Array.isArray(v.columns)&&Array.isArray(v.exceptions)&&v.columns.every(c=>Array.isArray(c.examples)&&Array.isArray(c.patterns)&&c.patterns.every(p=>Array.isArray(p)&&p.length===2)))return `<article class="visual-rule gender-rule"><h3>${esc(rule.title)}</h3><div class="gender-columns">${v.columns.map((c,index)=>`<section class="gender-column"><header><span class="rule-number">${index+1}</span><div><div class="gender-symbols"><i class="bi bi-person-fill" aria-hidden="true"></i><i class="bi bi-${['table','book-fill','heart-fill'][index]}" aria-hidden="true"></i></div><p>${c.examples.map(esc).join(' · ')}</p></div></header><h4>${esc(c.latin)} <span>(${esc(c.code)})</span></h4><p class="gender-label">${esc(c.label)}</p><table><caption class="sr-only">${esc(c.label)}: окончания и примеры</caption><thead><tr><th>Окончание</th><th>Пример</th></tr></thead><tbody>${c.patterns.map(([ending,example])=>`<tr><td>${esc(ending)}</td><td>${esc(example)}</td></tr>`).join('')}</tbody></table></section>`).join('')}</div><div class="rule-exceptions"><b>Запомните отдельно</b><div>${v.exceptions.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><details class="rule-details"><summary>Полное объяснение</summary><p>${esc(rule.text)}</p></details></article>`;
 if(v?.format==='conjugation'&&Array.isArray(v.groups)&&v.groups.length===4&&v.groups.every(g=>Array.isArray(g.forms)&&g.forms.length===6&&Array.isArray(g.related)))return `<article class="visual-rule conjugation-rule"><h3>${esc(rule.title)}</h3><div class="verb-overview"><table><caption>Личные окончания</caption><tbody><tr><td>ja <b>-m</b></td><td>my <b>-me</b></td></tr><tr><td>ty <b>-š</b></td><td>vy <b>-te</b></td></tr><tr><td>on/ona/ono <b>∅</b></td><td>oni/ony <b>-jú / -ia</b></td></tr></tbody></table><div class="quantity-note"><b>Долгота гласных</b><p>volať sa → vol<b>á</b>m sa<br>hovoriť → hovor<b>í</b>m<br>čítať → č<b>í</b>tam</p></div></div><div class="verb-groups">${v.groups.map((g,index)=>`<section class="verb-group"><div class="verb-group-title"><span class="verb-number">${['I','II','III','IV'][index]}</span><h4>${verbHighlight(g.verb,index,true)}</h4><img src="src/assets/illustrations/${['mascot-tablet','lesson-people','mascot-laptop','mascot-reading'][index]}.png" alt="" aria-hidden="true"></div><table><caption class="sr-only">${esc(g.verb)}: формы настоящего времени</caption><tbody>${[0,1,2].map(row=>`<tr><td><span>${['ja','ty','on/ona/ono'][row]}</span> <b>${verbHighlight(g.forms[row],index)}</b></td><td><span>${['my','vy','oni/ony'][row]}</span> <b>${verbHighlight(g.forms[row+3],index)}</b></td></tr>`).join('')}</tbody></table><div class="verb-related"><b>По этому образцу</b><p>${g.related.map(esc).join(' · ')}</p></div></section>`).join('')}</div><div class="verb-negative"><b>Отрицание</b><p>ne- + глагол, слитно: <strong>nehovorím · nerozumieme · nemám · nepoznáme</strong></p><p>У byť отдельно: <strong>nie som · nie si · nie je</strong></p></div><details class="rule-details"><summary>Полное объяснение</summary><p>${esc(rule.text)}</p></details></article>`;
 return `<article class="rule-preview"><h3>${esc(rule.title)}</h3><p>${esc(rule.text)}</p></article>`;
}
