const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function verbHighlight(text,index,title=false){
 const stems=title?['VOL','HOVOR','ŠTUD','ROZUM']:['vol','hovor','štud','rozum'];
 const value=String(text),stem=stems[index];
 if(!stem||!value.startsWith(stem))return esc(value);
 if(title){const tail=value.slice(stem.length),cut=tail.indexOf('Ť');if(cut>=0)return `${esc(stem)}<span class="verb-ending">${esc(tail.slice(0,cut))}</span>${esc(tail.slice(cut))}`;}
 const tail=value.slice(stem.length),space=tail.indexOf(' '),ending=space<0?tail:tail.slice(0,space),rest=space<0?'':tail.slice(space);
 return `${esc(stem)}<span class="verb-ending">${esc(ending)}</span>${esc(rest)}`;
}
const end=(stem,suffix)=>`${esc(stem)}<span class="nom-ending">${esc(suffix)}</span>`;
function nominativeCard(rule,personal=false){
 const head=personal?'Nominatív – osobné maskulína':'Nominatív';
 const rows=personal?[
 ['ten',end('pekn','-ý'),'muž<br>učiteľ<br>'+end('koleg','-a'),'t-'+end('','í'),end('pekn','-í'),end('muž','-i')+'<br>'+end('učiteľ','-ia')+'<br>'+end('koleg','-ovia')]
 ]:[
 ['ten',end('pekn','-ý'),'plán','počítač','t-ie',end('pekn','-é'),end('plán','-y'),end('počítač','-e')],
 ['tá',end('pekn','-á'),end('žen','-a'),end('stanic','-a'),'t-ie',end('pekn','-é'),end('žen','-y'),end('stanic','-e')],
 ['to',end('pekn','-é'),end('mest','-o'),'','t-ie',end('pekn','-é'),end('mest','-á'),'']];
 const footer=`<div class="nom-footer"><div>F　<b>loď →</b> lode, postele, garáže, jedálne<br>F　<b>miestnosť →</b> miestnosti, noci, veci<br>N　<b>námestie →</b> námestia, poschodia, cvičenia</div><div class="nom-quantity"><b>kvantita</b><div>miesto → miesta　 číslo → čísla<br>mlieko → mlieká　 vajíčko → vajíčka</div></div></div>`;
 const bubbles=personal?['-e- → -∅-<br>chlapec → chlapci<br>otec → otcovia','neprav.<br>človek → ľudia']:['-e- → -∅-<br>pes → psy<br>lekáreň → lekárne','-ô- → -o-<br>stôl → stoly<br>kôš → koše','-∅- → -at-<br>dievča → dievčatá','neprav.<br>dieťa → deti<br>deň → dni'];
 return `<article class="visual-rule nom-sheet"><h3>${head}</h3><div class="nom-layout"><div><div class="nom-labels"><span>singulár</span><span>plurál</span></div>${personal?'':`<div class="nom-paradigms"><span>paradigma<br><b>TVRDÁ　 MÄKKÁ</b></span><span>paradigma<br><b>TVRDÁ　 MÄKKÁ</b></span></div>`}<table class="nom-main"><thead><tr><th colspan="${personal?3:4}">KTO / ČO JE TO?</th><th colspan="${personal?3:4}">KTO / ČO SÚ TO?</th></tr></thead><tbody>${rows.map((row,r)=>`<tr>${row.map((c,i)=>`<td class="${(personal?[0,1,3,4]:[0,1,4,5]).includes(i)?'nom-blue':'nom-yellow'}"${!personal&&i===4&&r===0?' rowspan="3"':''}${!personal&&r===2&&[2,6].includes(i)?' colspan="2"':''}${!personal&&i===5&&r===0?' rowspan="3"':''}>${c}</td>`).filter((_,i)=>personal||(r===0)||(r===1?![4,5].includes(i):![3,4,5,7].includes(i))).join('')}</tr>`).join('')}</tbody></table>${!personal?footer:''}</div><aside class="nom-bubbles">${bubbles.map(b=>`<div>${b}</div>`).join('')}</aside></div>${personal?`<table class="nom-men"><thead><tr><th>-I</th><th>-IA</th><th>-OVIA</th></tr></thead><tbody><tr><td>profesori　 prezidenti　 lekári</td><td>rodičia　 manželia　 bratia<br>susedia　 hostia</td><td>dedovia　 otcovia　 synovia</td></tr></tbody></table><div class="nom-men-notes"><div><b>-k → -ci</b><br>speváci, hudobníci, technici<br><b>-ista → -isti</b><br>futbalisti, hokejisti, cyklisti</div><div><b>-teľ → -telia</b><br>učitelia, priatelia, obyvatelia<br><b>-an → -ania</b><br>Kanaďania, Američania, Belgičania</div><div><b>-a → -ovia</b><br>kolegovia, sudcovia, dôchodcovia<br><b>-lóg → -lógovia</b><br>filológovia, psychológovia</div></div>`:''}<details class="rule-details"><summary>Объяснение по-русски</summary><p>${esc(rule.text)}</p></details></article>`;
}

export function ruleCard(rule){const v=rule.visual;
 if(v?.format==='nominative')return nominativeCard(rule,v.personal);
 if(v?.format==='nationalities')return `<article class="visual-rule nom-sheet national-sheet"><table><thead><tr>${v.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${v.rows.map(row=>`<tr>${row.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table><details class="rule-details"><summary>Объяснение по-русски</summary><p>${esc(rule.text)}</p></details></article>`;
 if(v?.format==='reference-table'&&Array.isArray(v.headers)&&Array.isArray(v.rows))return `<article class="visual-rule reference-table-rule"><h3>${esc(rule.title)}</h3><div class="rule-table-scroll"><table><thead><tr>${v.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${v.rows.map(row=>`<tr>${row.map(cell=>`<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="reference-rule-note">${esc(rule.text)}</p></article>`;
 if(v?.format==='gender'&&v.image==='rule-rod.png')return `<article class="visual-rule image-rule"><h3>${esc(rule.title)}</h3><a href="src/assets/illustrations/rule-rod.png" target="_blank" rel="noopener" aria-label="Открыть таблицу рода в полном размере"><img loading="lazy" decoding="async" class="grammar-sheet" src="src/assets/illustrations/rule-rod.png" alt="Substantíva – rod: мужской, женский и средний род, окончания, примеры и исключения"></a><details class="rule-details"><summary>Полное объяснение</summary><p>${esc(rule.text)}</p></details></article>`;
 if(v?.format==='gender'&&Array.isArray(v.columns)&&Array.isArray(v.exceptions)&&v.columns.every(c=>Array.isArray(c.examples)&&Array.isArray(c.patterns)&&c.patterns.every(p=>Array.isArray(p)&&p.length===2)))return `<article class="visual-rule gender-rule"><h3>${esc(rule.title)}</h3><div class="gender-columns">${v.columns.map((c,index)=>`<section class="gender-column"><header><span class="rule-number">${index+1}</span><div><div class="gender-symbols"><i class="bi bi-person-fill" aria-hidden="true"></i><i class="bi bi-${['table','book-fill','heart-fill'][index]}" aria-hidden="true"></i></div><p>${c.examples.map(esc).join(' · ')}</p></div></header><h4>${esc(c.latin)} <span>(${esc(c.code)})</span></h4><p class="gender-label">${esc(c.label)}</p><table><caption class="sr-only">${esc(c.label)}: окончания и примеры</caption><thead><tr><th>Окончание</th><th>Пример</th></tr></thead><tbody>${c.patterns.map(([ending,example])=>`<tr><td>${esc(ending)}</td><td>${esc(example)}</td></tr>`).join('')}</tbody></table></section>`).join('')}</div><div class="rule-exceptions"><b>Запомните отдельно</b><div>${v.exceptions.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><details class="rule-details"><summary>Полное объяснение</summary><p>${esc(rule.text)}</p></details></article>`;
 if(v?.format==='conjugation'&&Array.isArray(v.groups)&&v.groups.length===4&&v.groups.every(g=>Array.isArray(g.forms)&&g.forms.length===6&&Array.isArray(g.related)))return `<article class="visual-rule conjugation-rule"><h3>${esc(rule.title)}</h3><div class="verb-overview"><table><caption>Личные окончания</caption><tbody><tr><td>ja <b>-m</b></td><td>my <b>-me</b></td></tr><tr><td>ty <b>-š</b></td><td>vy <b>-te</b></td></tr><tr><td>on/ona/ono <b>∅</b></td><td>oni/ony <b>-jú / -ia</b></td></tr></tbody></table><div class="quantity-note"><b>Долгота гласных</b><p>volať sa → vol<b>á</b>m sa<br>hovoriť → hovor<b>í</b>m<br>čítať → č<b>í</b>tam</p></div></div><div class="verb-groups">${v.groups.map((g,index)=>`<section class="verb-group"><div class="verb-group-title"><span class="verb-number">${['I','II','III','IV'][index]}</span><h4>${verbHighlight(g.verb,index,true)}</h4><img loading="lazy" decoding="async" src="src/assets/illustrations/${['mascot-tablet','lesson-people','mascot-laptop','mascot-reading'][index]}.webp" alt="" aria-hidden="true"></div><table><caption class="sr-only">${esc(g.verb)}: формы настоящего времени</caption><tbody>${[0,1,2].map(row=>`<tr><td><span>${['ja','ty','on/ona/ono'][row]}</span> <b>${verbHighlight(g.forms[row],index)}</b></td><td><span>${['my','vy','oni/ony'][row]}</span> <b>${verbHighlight(g.forms[row+3],index)}</b></td></tr>`).join('')}</tbody></table><div class="verb-related"><b>По этому образцу</b><p>${g.related.map(esc).join(' · ')}</p></div></section>`).join('')}</div><div class="verb-negative"><b>Отрицание</b><p>ne- + глагол, слитно: <strong>nehovorím · nerozumieme · nemám · nepoznáme</strong></p><p>У byť отдельно: <strong>nie som · nie si · nie je</strong></p></div><details class="rule-details"><summary>Полное объяснение</summary><p>${esc(rule.text)}</p></details></article>`;
 return `<article class="rule-preview"><h3>${esc(rule.title)}</h3><p>${esc(rule.text)}</p></article>`;
}
